/*
Package include imports all protos packages so that they register with the global
registry. This package can be imported in the main package to automatically register
all of the standard supported Packetbeat protocols.
*/
package include

import (
	// This list is automatically generated by `make imports`
	_ "packetbeat/protos/amqp"
	_ "packetbeat/protos/applayer"
	_ "packetbeat/protos/cassandra"
	_ "packetbeat/protos/dns"
	_ "packetbeat/protos/http"
	_ "packetbeat/protos/icmp"
	_ "packetbeat/protos/memcache"
	_ "packetbeat/protos/mongodb"
	_ "packetbeat/protos/mysql"
	_ "packetbeat/protos/nfs"
	_ "packetbeat/protos/pgsql"
	_ "packetbeat/protos/redis"
	_ "packetbeat/protos/tcp"
	_ "packetbeat/protos/thrift"
	_ "packetbeat/protos/udp"
)
